{
  ...
}:

{
  imports = [
    ./anki.nix
    ./btop.nix
    ./carla.nix
    ./discord.nix
    ./fastfetch/fastfetch.nix
    ./kdeconnect.nix
    ./kitty.nix
    ./mixxx.nix
    ./nvim.nix
    ./obs-studio.nix
    ./oh-my-posh.nix
    ./pavucontrol.nix
    ./qbittorrent.nix
    ./steam.nix
    ./telegram.nix
    ./vlc.nix
    ./vscode.nix
    ./wg-gui.nix
    ./winbox.nix
    ./yazi.nix
    ./zapret.nix
    ./zed.nix
    ./zen-browser.nix
  ];
}
